# Generated by Django 3.2.6 on 2021-10-18 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500, unique=True, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='name of product')),
                ('url', models.CharField(max_length=100, verbose_name='url of product')),
                ('nutrition_grade', models.CharField(max_length=100, verbose_name='nutrition grade of product')),
                ('image_url', models.URLField()),
                ('image_nutrition_url', models.URLField()),
                ('category_fk', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_fk', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('user_fk', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product_fk', 'user_fk')},
            },
        ),
    ]
