# Generated by Django 3.2.6 on 2021-10-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211022_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_fk',
        ),
    ]
