# Generated by Django 3.2.6 on 2021-10-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_code_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name of product'),
        ),
    ]
