# Generated by Django 3.2.6 on 2021-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=500, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(max_length=100, unique=True, verbose_name='code of product'),
        ),
    ]
