# Generated by Django 3.2.6 on 2021-11-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default=0, max_length=500, verbose_name='description of product'),
            preserve_default=False,
        ),
    ]
