# Generated by Django 3.2.6 on 2021-10-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnns_groups_1', models.CharField(max_length=500, verbose_name='category')),
                ('generic_name_fr', models.CharField(max_length=100, verbose_name='name of product')),
                ('url', models.CharField(max_length=100, verbose_name='url of product')),
                ('nutrition_grade_fr', models.CharField(max_length=100, verbose_name='nutrition grade of product')),
                ('image_url', models.URLField()),
                ('image_nutrition_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_products_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnns_groups_1', models.CharField(max_length=500, verbose_name='category')),
                ('code_products_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
    ]
