# Generated by Django 3.2.6 on 2021-10-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_code_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code_product',
        ),
    ]
