# Generated by Django 3.2.6 on 2021-10-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_product',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='code of product'),
            preserve_default=False,
        ),
    ]
