# Generated by Django 3.2.6 on 2021-10-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20211029_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=500, unique=True, verbose_name='category name'),
        ),
    ]
